#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=02:00:00
#SBATCH --job-name=bwa_bar5
#SBATCH --output=/share/BioinfMSc/rotation1/Group1/bash_scripts/slurm-%x-%j.out
#SBATCH --error=/share/BioinfMSc/rotation1/Group1/bash_scripts/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=alyjh38@nottingham.ac.uk

set -e 
set -x

source $HOME/.bash_profile

conda activate bwa_env

REF="/share/BioinfMSc/rotation1/Group1/Illumina/bar5output_rerun/assembly_bar05.fasta"
OUTDIR="/share/BioinfMSc/rotation1/Group1/Illumina/mapping_bar5"
FQ1="/share/BioinfMSc/rotation1/Group1/Illumina/bar5merged_forward.fastq.gz"
FQ2="/share/BioinfMSc/rotation1/Group1/Illumina/bar5merged_reverse.fastq.gz"

mkdir -p $OUTDIR

bwa index $REF

bwa mem -t 8 $REF $FQ1 $FQ2 > $OUTDIR/barcode05.sam

samtools view -Sb $OUTDIR/barcode05.sam | samtools sort -@ 8 -o $OUTDIR/barcode05_sorted.bam

samtools index $OUTDIR/barcode05_sorted.bam

samtools faidx $REF

conda deactivate

